/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contenedor;

/**
 *
 * @author diego
 */
public class FrmContenedor extends javax.swing.JFrame {

    /**
     * Creates new form FrmContenedor
     */
    public FrmContenedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DP_Workbench = new javax.swing.JDesktopPane();
        MBCont = new javax.swing.JMenuBar();
        MArch = new javax.swing.JMenu();
        MProc = new javax.swing.JMenu();
        MCat = new javax.swing.JMenu();
        MIMarc = new javax.swing.JMenuItem();
        MILin = new javax.swing.JMenuItem();
        MIBod = new javax.swing.JMenuItem();
        MIProv = new javax.swing.JMenuItem();
        MIVend = new javax.swing.JMenuItem();
        MInf = new javax.swing.JMenu();
        MHerr = new javax.swing.JMenu();
        MAyud = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("9959-19-19543 Diego Pablo Vásquez Vásquez");
        setResizable(false);

        DP_Workbench.setBackground(new java.awt.Color(51, 0, 51));

        javax.swing.GroupLayout DP_WorkbenchLayout = new javax.swing.GroupLayout(DP_Workbench);
        DP_Workbench.setLayout(DP_WorkbenchLayout);
        DP_WorkbenchLayout.setHorizontalGroup(
            DP_WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        DP_WorkbenchLayout.setVerticalGroup(
            DP_WorkbenchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        MArch.setText("Archivo");

        MProc.setText("Procesos");
        MArch.add(MProc);

        MBCont.add(MArch);

        MCat.setText("Catálogos");

        MIMarc.setText("Marcas");
        MIMarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMarcActionPerformed(evt);
            }
        });
        MCat.add(MIMarc);

        MILin.setText("Líneas");
        MILin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILinActionPerformed(evt);
            }
        });
        MCat.add(MILin);

        MIBod.setText("Bodegas");
        MIBod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIBodActionPerformed(evt);
            }
        });
        MCat.add(MIBod);

        MIProv.setText("Proveedores");
        MIProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIProvActionPerformed(evt);
            }
        });
        MCat.add(MIProv);

        MIVend.setText("Vendedores");
        MIVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIVendActionPerformed(evt);
            }
        });
        MCat.add(MIVend);

        MBCont.add(MCat);

        MInf.setText("Informes");
        MBCont.add(MInf);

        MHerr.setText("Herramientas");
        MBCont.add(MHerr);

        MAyud.setText("Ayuda");
        MBCont.add(MAyud);

        setJMenuBar(MBCont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DP_Workbench)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DP_Workbench)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MIBodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIBodActionPerformed
        FrmMantBod frmMB = new FrmMantBod();
        frmMB.setVisible(true);
        DP_Workbench.add(frmMB);
    }//GEN-LAST:event_MIBodActionPerformed

    private void MIMarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMarcActionPerformed
        FrmMantMarc frmMM = new FrmMantMarc();
        frmMM.setVisible(true);
        DP_Workbench.add(frmMM);
    }//GEN-LAST:event_MIMarcActionPerformed

    private void MILinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILinActionPerformed
        FrmMantLin frmML = new FrmMantLin();
        frmML.setVisible(true);
        DP_Workbench.add(frmML);
    }//GEN-LAST:event_MILinActionPerformed

    private void MIProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIProvActionPerformed
        FrmMantProv frmMP = new FrmMantProv();
        frmMP.setVisible(true);
        DP_Workbench.add(frmMP);
    }//GEN-LAST:event_MIProvActionPerformed

    private void MIVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIVendActionPerformed
        FrmMantVend frmMV = new FrmMantVend();
        frmMV.setVisible(true);
        DP_Workbench.add(frmMV);
    }//GEN-LAST:event_MIVendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DP_Workbench;
    private javax.swing.JMenu MArch;
    private javax.swing.JMenu MAyud;
    private javax.swing.JMenuBar MBCont;
    private javax.swing.JMenu MCat;
    private javax.swing.JMenu MHerr;
    private javax.swing.JMenuItem MIBod;
    private javax.swing.JMenuItem MILin;
    private javax.swing.JMenuItem MIMarc;
    private javax.swing.JMenuItem MIProv;
    private javax.swing.JMenuItem MIVend;
    private javax.swing.JMenu MInf;
    private javax.swing.JMenu MProc;
    // End of variables declaration//GEN-END:variables
}
